#ifndef MES_COLLECTOR_COLLECTOR_H
#define MES_COLLECTOR_COLLECTOR_H

#include <stddef.h>

#include "config.h"
#include "net.h"
#include "protocol.h"

typedef enum {
    COLLECTOR_FEED_OK = 0,
    COLLECTOR_FEED_CLOSE_CONNECTION = -1
} CollectorFeedResult;

typedef enum {
    COLLECTOR_SESSION_ERROR_PROTOCOL = 0,
    COLLECTOR_SESSION_ERROR_HELLO_REQUIRED,
    COLLECTOR_SESSION_ERROR_DUPLICATE_HELLO,
    COLLECTOR_SESSION_ERROR_MACHINE_ID_MISMATCH,
    COLLECTOR_SESSION_ERROR_MESSAGE_TOO_LONG
} CollectorSessionError;

typedef void (*CollectorMessageHandler)(const ProtocolMessage *message,
                                        void *context);
typedef void (*CollectorErrorHandler)(CollectorSessionError error,
                                      ProtocolResult protocol_result,
                                      const char *line,
                                      void *context);

typedef struct {
    CollectorMessageHandler on_message;
    CollectorErrorHandler on_error;
    void *context;
} CollectorSessionHandlers;

typedef struct {
    char machine_id[PROTOCOL_MACHINE_ID_CAPACITY];
    char line_buffer[COLLECTOR_MAX_MESSAGE_SIZE + 1];
    size_t line_length;
    int hello_received;
    int discarding_oversized_message;
} CollectorSession;

typedef enum {
    COLLECTOR_SEND_OK = 0,
    COLLECTOR_SEND_NOT_REGISTERED,
    COLLECTOR_SEND_MACHINE_ID_MISMATCH,
    COLLECTOR_SEND_INVALID_COMMAND,
    COLLECTOR_SEND_NETWORK_ERROR
} CollectorSendResult;

typedef enum {
    COLLECTOR_COMM_DISCONNECTED = 0,
    COLLECTOR_COMM_TIMEOUT
} CollectorCommunicationFailure;

void collector_session_init(CollectorSession *session);

/*
 * Adds arbitrary TCP bytes to a session. Complete LF-terminated messages are
 * parsed and delivered through the handlers. A TCP recv() call may contain a
 * partial message or several messages, so callers must not assume 1:1 framing.
 */
CollectorFeedResult collector_session_feed(
    CollectorSession *session,
    const void *data,
    size_t length,
    const CollectorSessionHandlers *handlers);

/* Builds and sends one COMMAND to the L1 registered on this session. */
CollectorSendResult collector_send_command(const CollectorSession *session,
                                           NetSocket client_socket,
                                           const ProtocolCommand *command,
                                           ProtocolResult *protocol_result);

/* Finds the registered connection by MACHINE_ID and sends one COMMAND. */
CollectorSendResult collector_send_command_to_machine(
    const ProtocolCommand *command,
    ProtocolResult *protocol_result);

/* Builds the two Backend events generated by L2 for an L1 communication fault. */
int collector_build_communication_failure_events(
    const char *machine_id,
    CollectorCommunicationFailure failure,
    ProtocolMessage *alarm,
    ProtocolMessage *machine_status);

/* Runs the multi-L1 accept loop with one worker and timeout per connection. */
int collector_run(void);

#endif
