#ifndef MES_COLLECTOR_CONFIG_H
#define MES_COLLECTOR_CONFIG_H

/* L1 -> L2 TCP settings (docs/tcp-protocol.md v0.4). */
#define COLLECTOR_BIND_ADDRESS "0.0.0.0"
#define COLLECTOR_TCP_PORT 9000
#define COLLECTOR_MAX_L1_CONNECTIONS 6
#define COLLECTOR_MAX_MESSAGE_SIZE 1024
#define COLLECTOR_HELLO_TIMEOUT_SECONDS 5
#define COLLECTOR_HEARTBEAT_INTERVAL_SECONDS 5
#define COLLECTOR_COMM_TIMEOUT_SECONDS 15
#define COLLECTOR_RECONNECT_DELAY_SECONDS 3

/* L2 -> Backend HTTP settings (backend/application.properties). */
#define MES_BACKEND_ADDRESS "127.0.0.1"
#define MES_BACKEND_PORT 8111
#define MES_BACKEND_BASE_URL "http://127.0.0.1:8111"
#define MES_HTTP_CONNECT_TIMEOUT_SECONDS 3
#define MES_HTTP_REQUEST_TIMEOUT_SECONDS 5
#define MES_HTTP_MAX_RETRIES 2
#define MES_HTTP_RETRY_DELAY_MILLISECONDS 500
#define MES_HTTP_QUEUE_RETRY_INTERVAL_SECONDS 3
#define MES_HTTP_RETRY_QUEUE_FILE "mes_http_retry.queue"
#define MES_HTTP_DEAD_LETTER_FILE "mes_http_dead_letter.queue"
#define COMMAND_POLL_INTERVAL_SECONDS 1

#endif
