import React, { useState } from "react";
import MesApi from "../api/MesApi";
import useApiData from "../hooks/useApiData";
import { EmptyState, ErrorState, Field, LoadingState, Modal, PageHeader, StatusBadge, formatDate } from "../components/MesComponents";

export default function AdminEmployeePage(){
  const result=useApiData(MesApi.getMembers,[]); const [form,setForm]=useState(null); const [temporary,setTemporary]=useState(null); const [error,setError]=useState(null); const [saving,setSaving]=useState(false);
  const save=async()=>{setSaving(true);setError(null);try{if(form.memberId){await MesApi.updateMember(form.memberId,{role:form.role,status:form.status,department:form.department,position:form.position})}else{await MesApi.createMember(form)}setForm(null);await result.reload()}catch(e){setError(e)}finally{setSaving(false)}};
  const reset=async(member)=>{if(!window.confirm(`${member.memberName} 사용자의 비밀번호를 초기화할까요?`))return;setError(null);try{const r=await MesApi.resetMemberPassword(member.memberId);setTemporary(r.data)}catch(e){setError(e)}};
  return <div className="mes-page"><PageHeader title="사용자 관리" description="ADMIN 전용 계정·권한 관리 화면입니다." actions={<button className="btn" onClick={()=>setForm({loginId:"",password:"",memberName:"",role:"VIEWER",status:"ACTIVE",department:"",position:""})}>사용자 등록</button>}/>
    {error&&<ErrorState error={error}/>} {result.loading?<LoadingState/>:result.error?<ErrorState error={result.error} onRetry={result.reload}/>:!(result.data||[]).length?<EmptyState/>:<div className="mes-table-wrap"><table className="mes-table"><thead><tr><th>로그인 ID/이름</th><th>역할</th><th>상태</th><th>부서/직급</th><th>생성자</th><th>수정 시각</th><th>작업</th></tr></thead><tbody>{result.data.map(m=><tr key={m.memberId}><td><span className="mono">{m.loginId}</span><br/><strong>{m.memberName}</strong></td><td><StatusBadge value={m.role}/></td><td><StatusBadge value={m.status}/></td><td>{m.department||"-"} / {m.position||"-"}</td><td>{m.createdByName||"-"}</td><td>{formatDate(m.updatedAt)}</td><td><div className="mes-actions"><button className="btn small secondary" onClick={()=>setForm({...m})}>수정</button><button className="btn small" onClick={()=>reset(m)}>비밀번호 초기화</button></div></td></tr>)}</tbody></table></div>}
    {form&&<Modal title={form.memberId?"사용자 수정":"사용자 등록"} onClose={()=>setForm(null)} footer={<><button className="btn secondary" onClick={()=>setForm(null)}>취소</button><button className="btn" disabled={saving} onClick={save}>저장</button></>}><div className="mes-form-grid">{!form.memberId&&<><Field label="로그인 ID"><input value={form.loginId} onChange={e=>setForm({...form,loginId:e.target.value})}/></Field><Field label="초기 비밀번호"><input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></Field><Field label="이름"><input value={form.memberName} onChange={e=>setForm({...form,memberName:e.target.value})}/></Field></>}<Field label="역할"><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{["ADMIN","MANAGER","OPERATOR","VIEWER"].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="상태"><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{["ACTIVE","LOCKED","RETIRED"].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="부서"><input value={form.department||""} onChange={e=>setForm({...form,department:e.target.value})}/></Field><Field label="직급"><input value={form.position||""} onChange={e=>setForm({...form,position:e.target.value})}/></Field></div>{error&&<ErrorState error={error}/>}</Modal>}
    {temporary&&<Modal title="임시 비밀번호 발급 완료" onClose={()=>setTemporary(null)} footer={<button className="btn" onClick={()=>setTemporary(null)}>확인</button>}><p>{temporary.loginId} 사용자의 임시 비밀번호입니다. 닫으면 다시 표시되지 않습니다.</p><div className="mes-card mono" style={{fontSize:20,textAlign:"center"}}>{temporary.temporaryPassword}</div><button className="btn secondary" onClick={()=>navigator.clipboard.writeText(temporary.temporaryPassword)}>복사</button></Modal>}
  </div>
}
