import React, { useEffect, useMemo, useState } from "react";
import MesApi from "../api/MesApi";
import useApiData from "../hooks/useApiData";
import { EmptyState, ErrorState, Field, LoadingState, PageHeader, StatusBadge, formatDate } from "../components/MesComponents";

const processCodes=["OP20","OP30","OP40_OP50","OP60","OP70","OP80"];

export default function LotPage({currentUser}){
  const [status,setStatus]=useState(""); const [selected,setSelected]=useState(null); const [detail,setDetail]=useState(null); const [detailError,setDetailError]=useState(null); const [loadingDetail,setLoadingDetail]=useState(false); const [tab,setTab]=useState("progress"); const [saving,setSaving]=useState(false); const [actionError,setActionError]=useState(null);
  const list=useApiData(()=>MesApi.getLots({status}),[status]);
  const canStart=["ADMIN","MANAGER","OPERATOR"].includes(currentUser?.role);
  const startProduction=async(lot)=>{setSaving(true);setActionError(null);try{const response=await MesApi.updateLotStatus(lot.lotId,"RUNNING");setSelected(response.data);await list.reload()}catch(error){setActionError(error)}finally{setSaving(false)}};
  useEffect(()=>{ if(!selected){setDetail(null);return;} let active=true; setLoadingDetail(true); setDetailError(null); Promise.all([MesApi.getLotByNo(selected.lotNo),MesApi.getLotCommands(selected.lotNo),MesApi.getLotResponsibles(selected.lotNo),MesApi.getProductionLogs({lotNo:selected.lotNo}),MesApi.getInspections({lotNo:selected.lotNo}),MesApi.getDefects({lotNo:selected.lotNo})]).then(([lot,commands,responsibles,logs,inspections,defects])=>{if(active)setDetail({lot:lot.data,commands:commands.data,responsibles:responsibles.data,logs:logs.data,inspections:inspections.data,defects:defects.data})}).catch(e=>active&&setDetailError(e)).finally(()=>active&&setLoadingDetail(false)); return()=>{active=false};},[selected]);
  const progress=useMemo(()=>detail?buildProgress(detail.lot,detail.logs,detail.inspections):[],[detail]);
  return <div className="mes-page"><PageHeader title="LOT 추적" description="LOT의 공정, 작업명령, 생산·검사·불량 이력을 추적합니다." actions={<button className="btn secondary" onClick={list.reload}>새로고침</button>}/>
    <div className="mes-card mes-filter"><Field label="LOT 상태"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">전체</option>{["WAITING","RUNNING","COMPLETED","HOLD","SCRAPPED"].map(v=><option key={v}>{v}</option>)}</select></Field></div>
    {actionError&&<ErrorState error={actionError}/>} {list.loading?<LoadingState/>:list.error?<ErrorState error={list.error} onRetry={list.reload}/>:<div className="split-detail"><div className="mes-table-wrap"><table className="mes-table"><thead><tr><th>LOT</th><th>작업지시/품목</th><th>유형</th><th>현재 공정</th><th>수량</th><th>상태</th><th>작업</th></tr></thead><tbody>{(list.data||[]).map(l=><tr key={l.lotId} onClick={()=>setSelected(l)} style={{cursor:"pointer",background:selected?.lotId===l.lotId?"#eff6ff":""}}><td><strong>{l.lotNo}</strong><br/><span className="mono">#{l.lotId}</span></td><td>{l.orderNo}<br/>{l.itemName}</td><td><StatusBadge value={l.lotType}/> #{l.productionRound}</td><td>{l.currentProcessName}<br/><span className="mono">{l.currentProcessCode}</span></td><td>{l.inputQty} / OK {l.okQty} / NG {l.ngQty}</td><td><StatusBadge value={l.status}/></td><td>{canStart&&l.status==="WAITING"?<button className="btn small" disabled={saving} onClick={event=>{event.stopPropagation();startProduction(l)}}>생산 시작</button>:"-"}</td></tr>)}</tbody></table></div><aside className="mes-card">{!selected?<EmptyState message="LOT를 선택하면 상세 정보가 표시됩니다."/>:loadingDetail?<LoadingState/>:detailError?<ErrorState error={detailError}/>:detail&&<LotSummary lot={detail.lot}/>}</aside></div>}
    {detail&&<section className="mes-card"><div className="tabs">{[["progress","공정 진행"],["commands","작업명령"],["logs","생산 실적"],["quality","검사·불량"],["people","담당자"]].map(([key,label])=><button key={key} className={`tab ${tab===key?"active":""}`} onClick={()=>setTab(key)}>{label}</button>)}</div><div style={{paddingTop:16}}>{tab==="progress"&&<ProgressView rows={progress}/>} {tab==="commands"&&<Commands rows={detail.commands}/>} {tab==="logs"&&<Logs rows={detail.logs}/>} {tab==="quality"&&<Quality inspections={detail.inspections} defects={detail.defects}/>} {tab==="people"&&<People rows={detail.responsibles}/>}</div></section>}
  </div>;
}

function LotSummary({lot}){return <><h2>{lot.lotNo}</h2><dl className="detail-list"><dt>상태</dt><dd><StatusBadge value={lot.status}/></dd><dt>작업지시</dt><dd>{lot.orderNo}</dd><dt>품목</dt><dd>{lot.itemName} ({lot.itemCode})</dd><dt>현재 공정</dt><dd>{lot.currentProcessName} ({lot.currentProcessCode})</dd><dt>투입 수량</dt><dd>{lot.inputQty}</dd><dt>최종 OK / NG</dt><dd>{lot.okQty} / {lot.ngQty}</dd><dt>시작</dt><dd>{formatDate(lot.startedAt)}</dd><dt>완료</dt><dd>{formatDate(lot.completedAt)}</dd></dl></>}
function ProgressView({rows}){return <div className="mes-grid">{rows.map(r=><div key={r.code}><div style={{display:"flex",justifyContent:"space-between",marginBottom:6}}><strong>{r.code} · {r.name}</strong><span>{r.processed}/{r.target} · {r.percent}%</span></div><div className="progress-track"><span style={{width:`${r.percent}%`}}/></div><small style={{color:"#64748b"}}>OK {r.ok} · NG {r.ng} · {r.note}</small></div>)}</div>}
function Commands({rows=[]}){return <Table heads={["명령","설비/공정","수량","상태","ACK","시각"]} rows={rows.map(r=>[r.commandType,`${r.machineId} / ${r.processCode}`,r.inputQty,<StatusBadge value={r.status}/>,r.ackMessage||"-",formatDate(r.createdAt)])}/>}
function Logs({rows=[]}){return <Table heads={["공정","설비","투입","OK","NG","상태","종료"]} rows={rows.map(r=>[r.processCode,r.machineId,r.inputQty,r.okQty,r.ngQty,<StatusBadge value={r.status}/>,formatDate(r.endedAt)])}/>}
function Quality({inspections=[],defects=[]}){return <div className="mes-grid two"><div><h3>검사 결과</h3><Table heads={["순번","항목","측정값","기준","결과"]} rows={inspections.map(r=>[r.unitSeq,r.inspectionItem,`${r.measuredValue} ${r.unit}`,`${r.lowerLimit}~${r.upperLimit}`,<StatusBadge value={r.result}/>])}/></div><div><h3>불량 이력</h3><Table heads={["공정","코드","수량","발생"]} rows={defects.map(r=>[r.processCode,r.defectName||r.defectCode,r.defectQty,formatDate(r.occurredAt)])}/></div></div>}
function People({rows=[]}){return <Table heads={["공정","설비","작업자","역할","배정 시각"]} rows={rows.map(r=>[`${r.processName} (${r.processCode})`,r.machineName||r.machineId,`${r.workerName} (${r.workerNo})`,r.assignmentRole||"-",formatDate(r.capturedAt)])}/>}
function Table({heads,rows}){if(!rows.length)return <EmptyState/>;return <div className="mes-table-wrap"><table className="mes-table"><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div>}
function buildProgress(lot,logs,inspections){const sums={}; for(const code of processCodes)sums[code]={input:0,ok:0,ng:0}; (logs||[]).forEach(l=>{const s=sums[l.processCode];if(s){s.input+=l.inputQty||0;s.ok+=l.okQty||0;s.ng+=l.ngQty||0}}); const targets={OP20:lot.inputQty,OP30:lot.inputQty}; targets.OP40_OP50=Math.min(sums.OP20.ok,sums.OP30.ok); targets.OP60=sums.OP40_OP50.ok; targets.OP70=sums.OP60.ok; targets.OP80=sums.OP70.ok; const names={OP20:"코일 권선",OP30:"접점 용접",OP40_OP50:"자동 조립",OP60:"실링/가스충전",OP70:"최종 검사",OP80:"마킹/포장"}; return processCodes.map(code=>{const target=targets[code]||0;const inspected=code==="OP70"?new Set((inspections||[]).map(i=>i.unitSeq)).size:0;const processed=Math.max(sums[code].input,inspected);return{code,name:names[code],target,processed,ok:sums[code].ok,ng:sums[code].ng,percent:target?Math.min(100,Math.round(processed/target*100)):0,note:processed===0&&lot.currentProcessCode===code?"정상 가동 중 중간 수량은 완료·중단 이벤트 전까지 갱신되지 않습니다.":"Backend 누적 실적 기준"}})}
