import React, { useMemo, useState } from "react";
import MesApi from "../api/MesApi";
import useApiData from "../hooks/useApiData";
import { EmptyState, ErrorState, Field, LoadingState, Modal, PageHeader, StatusBadge, formatDate } from "../components/MesComponents";

export default function MaterialPage({currentUser}){
  const result=useApiData(MesApi.getMaterialLots,[]); const [form,setForm]=useState(null); const [saving,setSaving]=useState(false); const [actionError,setActionError]=useState(null);
  const items=useApiData(MesApi.getItems,[]);
  const materials=(items.data||[]).filter(item=>item.itemType==="RM"&&item.useYn==="Y");
  const summary=useMemo(()=>{const rows=result.data||[];return{available:rows.filter(r=>r.status==="AVAILABLE").reduce((n,r)=>n+(r.currentQty||0),0),hold:rows.filter(r=>r.status==="HOLD").reduce((n,r)=>n+(r.currentQty||0),0),items:new Set(rows.map(r=>r.itemCode)).size}},[result.data]);
  const canManage=["ADMIN","MANAGER","OPERATOR"].includes(currentUser?.role);
  const run=async(action)=>{setSaving(true);setActionError(null);try{await action();await result.reload();return true}catch(e){setActionError(e);return false}finally{setSaving(false)}};
  const create=async()=>{const ok=await run(()=>MesApi.createMaterialLot({...form,receivedQty:Number(form.receivedQty),receivedBy:currentUser.memberId}));if(ok)setForm(null)};
  return <div className="mes-page"><PageHeader title="자재 LOT" description="자재 입고 LOT와 현재 가용 수량을 Backend 기준으로 관리합니다." actions={<><button className="btn secondary" onClick={()=>{result.reload();items.reload()}}>새로고침</button>{canManage&&<button className="btn" disabled={items.loading} onClick={()=>setForm({materialLotNo:"",itemCode:"",receivedQty:""})}>자재 입고</button>}</>}/>
    <div className="mes-grid kpis"><Kpi label="품목 수" value={summary.items}/><Kpi label="사용 가능 수량" value={summary.available}/><Kpi label="HOLD 수량" value={summary.hold}/><Kpi label="부족 판단 기준" value="10 이하"/></div>
    {actionError&&<ErrorState error={actionError}/>} {result.loading?<LoadingState/>:result.error?<ErrorState error={result.error} onRetry={result.reload}/>:!(result.data||[]).length?<EmptyState/>:<div className="mes-table-wrap"><table className="mes-table"><thead><tr><th>자재 LOT</th><th>품목</th><th>입고</th><th>현재</th><th>상태</th><th>입고 처리</th><th>작업</th></tr></thead><tbody>{result.data.map(r=><tr key={r.materialLotId}><td><strong>{r.materialLotNo}</strong><br/><span className="mono">#{r.materialLotId}</span></td><td>{r.itemName}<br/><span className="mono">{r.itemCode}</span></td><td>{r.receivedQty}</td><td><strong style={{color:r.status==="AVAILABLE"&&r.currentQty<=10?"#dc2626":"inherit"}}>{r.currentQty}</strong></td><td><StatusBadge value={r.status}/></td><td>{r.receivedBy}<br/>{formatDate(r.receivedAt)}</td><td>{canManage?<select value={r.status} onChange={e=>run(()=>MesApi.updateMaterialLotStatus(r.materialLotId,e.target.value))} disabled={saving}>{["AVAILABLE","HOLD","USED","DISCARDED"].map(v=><option key={v}>{v}</option>)}</select>:"-"}</td></tr>)}</tbody></table></div>}
    {form&&<Modal title="자재 LOT 입고" onClose={()=>setForm(null)} footer={<><button className="btn secondary" onClick={()=>setForm(null)}>취소</button><button className="btn" disabled={saving||!form.materialLotNo||!form.itemCode||Number(form.receivedQty)<=0} onClick={create}>등록</button></>}><div className="mes-form-grid"><Field label="자재 LOT 번호"><input value={form.materialLotNo} onChange={e=>setForm({...form,materialLotNo:e.target.value})}/></Field><Field label="자재(코드)"><select value={form.itemCode} onChange={e=>setForm({...form,itemCode:e.target.value})}><option value="">원자재 선택</option>{materials.map(item=><option key={item.itemCode} value={item.itemCode}>{item.itemName} ({item.itemCode})</option>)}</select></Field><Field label="입고 수량"><input type="number" min="1" value={form.receivedQty} onChange={e=>setForm({...form,receivedQty:e.target.value})}/></Field></div>{items.error&&<ErrorState error={items.error}/>} {actionError&&<ErrorState error={actionError}/>}</Modal>}
  </div>
}
function Kpi({label,value}){return <div className="mes-card mes-kpi"><span className="label">{label}</span><strong className="value">{value}</strong></div>}
