import React, { useState } from "react";
import MesApi from "../api/MesApi";
import useApiData from "../hooks/useApiData";
import { EmptyState, ErrorState, Field, LoadingState, Modal, PageHeader, StatusBadge, formatDate } from "../components/MesComponents";

export default function QualityPage({currentUser}){
  const [tab,setTab]=useState("inspections"); const [filters,setFilters]=useState({lotNo:"",machineId:"",processCode:"",result:""}); const [applied,setApplied]=useState({}); const [edit,setEdit]=useState(null); const [actionError,setActionError]=useState(null);
  const inspections=useApiData(()=>MesApi.getInspections(applied),[JSON.stringify(applied)]); const defects=useApiData(()=>MesApi.getDefects(applied),[JSON.stringify(applied)]); const standards=useApiData(MesApi.getInspectionStandards,[]);
  const active=tab==="inspections"?inspections:tab==="defects"?defects:standards; const canEdit=["ADMIN","MANAGER"].includes(currentUser?.role);
  const saveLimits=async()=>{setActionError(null);try{await MesApi.updateInspectionLimits(edit.standardId,{lowerLimit:Number(edit.lowerLimit),upperLimit:Number(edit.upperLimit)});setEdit(null);standards.reload()}catch(e){setActionError(e)}};
  return <div className="mes-page"><PageHeader title="품질 관리" description="OP70 검사 결과, 공정 불량 이력과 검사 기준을 조회합니다." actions={<button className="btn secondary" onClick={active.reload}>새로고침</button>}/>
    <div className="tabs">{[["inspections","검사 결과"],["defects","불량 이력"],["standards","검사 기준"]].map(([k,l])=><button key={k} className={`tab ${tab===k?"active":""}`} onClick={()=>setTab(k)}>{l}</button>)}</div>
    {tab!=="standards"&&<div className="mes-card mes-filter"><Field label="LOT"><input value={filters.lotNo} onChange={e=>setFilters({...filters,lotNo:e.target.value})}/></Field><Field label="설비"><input value={filters.machineId} onChange={e=>setFilters({...filters,machineId:e.target.value})} placeholder="EQ-TEST-01"/></Field><Field label="공정"><input value={filters.processCode} onChange={e=>setFilters({...filters,processCode:e.target.value})} placeholder="OP70"/></Field>{tab==="inspections"&&<Field label="결과"><select value={filters.result} onChange={e=>setFilters({...filters,result:e.target.value})}><option value="">전체</option><option>OK</option><option>NG</option></select></Field>}<button className="btn" onClick={()=>setApplied({...filters})}>조회</button></div>}
    {active.loading?<LoadingState/>:active.error?<ErrorState error={active.error} onRetry={active.reload}/>:tab==="inspections"?<InspectionTable rows={inspections.data}/>:tab==="defects"?<DefectTable rows={defects.data}/>:<StandardTable rows={standards.data} canEdit={canEdit} onEdit={setEdit}/>}
    {edit&&<Modal title="검사 기준 수정" onClose={()=>setEdit(null)} footer={<><button className="btn secondary" onClick={()=>setEdit(null)}>취소</button><button className="btn" onClick={saveLimits}>저장</button></>}><p><strong>{edit.inspectionItem}</strong> · {edit.unit}</p><div className="mes-form-grid"><Field label="하한"><input type="number" step="any" value={edit.lowerLimit} onChange={e=>setEdit({...edit,lowerLimit:e.target.value})}/></Field><Field label="상한"><input type="number" step="any" value={edit.upperLimit} onChange={e=>setEdit({...edit,upperLimit:e.target.value})}/></Field></div>{actionError&&<ErrorState error={actionError}/>}</Modal>}
  </div>
}
function InspectionTable({rows=[]}){if(!rows.length)return <EmptyState/>;return <div className="mes-table-wrap"><table className="mes-table"><thead><tr><th>LOT/제품 순번</th><th>설비·공정</th><th>검사 항목</th><th>측정값</th><th>기준 범위</th><th>버전</th><th>결과</th><th>검사 시각</th></tr></thead><tbody>{rows.map(r=><tr key={r.inspectionId}><td><span className="mono">{r.lotNo}</span><br/>#{r.unitSeq}</td><td>{r.machineName}<br/><span className="mono">{r.machineId} · {r.processCode}</span></td><td>{r.inspectionItem}</td><td><strong>{r.measuredValue}</strong> {r.unit}</td><td>{r.lowerLimit} ~ {r.upperLimit}</td><td>v{r.standardVersion}</td><td><StatusBadge value={r.result}/></td><td>{formatDate(r.inspectedAt)}</td></tr>)}</tbody></table></div>}
function DefectTable({rows=[]}){if(!rows.length)return <EmptyState/>;return <div className="mes-table-wrap"><table className="mes-table"><thead><tr><th>LOT</th><th>설비·공정</th><th>불량 코드/명</th><th>수량</th><th>메시지</th><th>발생 시각</th></tr></thead><tbody>{rows.map(r=><tr key={r.defectHistoryId}><td className="mono">{r.lotNo}</td><td>{r.machineName}<br/><span className="mono">{r.machineId} · {r.processCode}</span></td><td>{r.defectName}<br/><span className="mono">{r.defectCode}</span></td><td>{r.defectQty}</td><td>{r.message||"-"}</td><td>{formatDate(r.occurredAt)}</td></tr>)}</tbody></table></div>}
function StandardTable({rows=[],canEdit,onEdit}){if(!rows.length)return <EmptyState/>;return <div className="mes-table-wrap"><table className="mes-table"><thead><tr><th>공정</th><th>품목</th><th>검사 항목</th><th>단위</th><th>하한</th><th>상한</th><th>버전</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.standardId}><td>{r.processName}<br/><span className="mono">{r.processCode}</span></td><td>{r.itemName}</td><td>{r.inspectionItem}</td><td>{r.unit}</td><td>{r.lowerLimit}</td><td>{r.upperLimit}</td><td>v{r.standardVersion}</td><td>{canEdit&&<button className="btn small secondary" onClick={()=>onEdit({...r})}>기준 수정</button>}</td></tr>)}</tbody></table></div>}
