import React, { useEffect, useState } from "react";
import MesApi from "../api/MesApi";
import useApiData from "../hooks/useApiData";
import { EmptyState, ErrorState, Field, LoadingState, Modal, PageHeader, StatusBadge, formatDate } from "../components/MesComponents";

export default function WorkerAssignmentPage({currentUser}){
  const machines=useApiData(MesApi.getMachines,[]), workers=useApiData(()=>MesApi.getWorkers({}),[]); const [machineId,setMachineId]=useState(""); const [assignments,setAssignments]=useState([]); const [loading,setLoading]=useState(false); const [error,setError]=useState(null); const [workerId,setWorkerId]=useState(""); const [mode,setMode]=useState("worker"); const [workerForm,setWorkerForm]=useState(null); const canEdit=["ADMIN","MANAGER"].includes(currentUser?.role);
  useEffect(()=>{if(!machineId){setAssignments([]);return;}setLoading(true);MesApi.getMachineAssignments(machineId).then(r=>setAssignments(r.data)).catch(setError).finally(()=>setLoading(false))},[machineId]);
  const reload=async()=>{if(machineId){const r=await MesApi.getMachineAssignments(machineId);setAssignments(r.data)}workers.reload()};
  const assign=async()=>{setError(null);try{if(mode==="responsible")await MesApi.assignResponsible(machineId,workerId);else await MesApi.addMachineWorker(machineId,workerId);setWorkerId("");await reload()}catch(e){setError(e)}};
  const saveWorker=async()=>{setError(null);try{const data={...workerForm,status:workerForm.status||"ACTIVE"};if(workerForm.workerId)await MesApi.updateWorker(workerForm.workerId,data);else await MesApi.createWorker(data);setWorkerForm(null);workers.reload()}catch(e){setError(e)}};
  return <div className="mes-page"><PageHeader title="작업자 배정" description="작업자 마스터와 설비별 책임자·작업자 배정을 관리합니다." actions={canEdit&&<button className="btn" onClick={()=>setWorkerForm({workerNo:"",workerName:"",department:"",position:"",status:"ACTIVE"})}>작업자 등록</button>}/>
    <div className="mes-grid two"><section className="mes-card"><h2>설비별 배정</h2><div className="mes-filter"><Field label="설비"><select value={machineId} onChange={e=>setMachineId(e.target.value)}><option value="">설비 선택</option>{(machines.data||[]).map(m=><option key={m.machineId} value={m.machineId}>{m.machineId} · {m.processName}</option>)}</select></Field>{canEdit&&<><Field label="작업자"><select value={workerId} onChange={e=>setWorkerId(e.target.value)}><option value="">작업자 선택</option>{(workers.data||[]).filter(w=>w.status==="ACTIVE").map(w=><option key={w.workerId} value={w.workerId}>{w.workerName} ({w.workerNo})</option>)}</select></Field><Field label="배정 유형"><select value={mode} onChange={e=>setMode(e.target.value)}><option value="worker">작업자</option><option value="responsible">책임자</option></select></Field><button className="btn" disabled={!machineId||!workerId} onClick={assign}>배정</button></>}</div>{error&&<ErrorState error={error}/>} {loading?<LoadingState/>:!machineId?<EmptyState message="설비를 선택하세요."/>:!assignments.length?<EmptyState message="배정된 작업자가 없습니다."/>:<div className="mes-table-wrap"><table className="mes-table"><thead><tr><th>작업자</th><th>부서/직급</th><th>역할</th><th>배정</th><th></th></tr></thead><tbody>{assignments.map(a=><tr key={a.assignmentId}><td>{a.workerName}<br/><span className="mono">{a.workerNo}</span></td><td>{a.department} / {a.position}</td><td>{a.assignmentRole}</td><td>{formatDate(a.assignedAt)}</td><td>{canEdit&&<button className="btn small danger" onClick={async()=>{await MesApi.removeMachineWorker(machineId,a.workerId);reload()}}>해제</button>}</td></tr>)}</tbody></table></div>}</section>
    <section className="mes-card"><h2>작업자 목록</h2>{workers.loading?<LoadingState/>:workers.error?<ErrorState error={workers.error}/>:<div className="mes-table-wrap"><table className="mes-table"><thead><tr><th>사번/이름</th><th>부서</th><th>직급</th><th>상태</th><th></th></tr></thead><tbody>{(workers.data||[]).map(w=><tr key={w.workerId}><td><span className="mono">{w.workerNo}</span><br/>{w.workerName}</td><td>{w.department}</td><td>{w.position}</td><td><StatusBadge value={w.status}/></td><td>{canEdit&&<button className="btn small secondary" onClick={()=>setWorkerForm({...w})}>수정</button>}</td></tr>)}</tbody></table></div>}</section></div>
    {workerForm&&<Modal title={workerForm.workerId?"작업자 수정":"작업자 등록"} onClose={()=>setWorkerForm(null)} footer={<><button className="btn secondary" onClick={()=>setWorkerForm(null)}>취소</button><button className="btn" disabled={!workerForm.workerNo?.trim()||!workerForm.workerName?.trim()||!workerForm.department?.trim()||!workerForm.position?.trim()} onClick={saveWorker}>저장</button></>}><div className="mes-form-grid"><Field label="사번"><input value={workerForm.workerNo} onChange={e=>setWorkerForm({...workerForm,workerNo:e.target.value})}/></Field><Field label="이름"><input value={workerForm.workerName} onChange={e=>setWorkerForm({...workerForm,workerName:e.target.value})}/></Field><Field label="부서 (필수)"><input value={workerForm.department||""} onChange={e=>setWorkerForm({...workerForm,department:e.target.value})}/></Field><Field label="직급 (필수)"><input value={workerForm.position||""} onChange={e=>setWorkerForm({...workerForm,position:e.target.value})}/></Field></div>{error&&<ErrorState error={error}/>}</Modal>}
  </div>
}
